version: '2'
services:
  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=btg_dev
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  web:
    build: .
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec unicorn -p 3000"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    links:
      - db
      - redis
